{
 "title": "DHT22 - home/temperature-humidity",
 "time": { "from": "2025-03-23T13:43:04.170Z", "to": "2025-03-23T15:19:45.191Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> yield(name: \"humidity_values\")\r\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> yield(name: \"humidity_values\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature Celsius",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureCelsius\")\r\n  |> yield(name: \"humidity_values\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature Fahrenheit",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureFahrenheit\")\r\n  |> yield(name: \"humidity_values\")\r\n"
    }
   ]
  },
  {
   "title": "Temperature Kelvin",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureKelvin\")\r\n  |> yield(name: \"humidity_values\")\r\n"
    }
   ]
  },
  {
   "title": "Average Temperature (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home/temperature-humidity\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureCelsius\" \r\n                    or r[\"_field\"] == \"temperatureKelvin\"\r\n                    or r[\"_field\"] == \"temperatureFahrenheit\")\r\n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"temperature_10m_mean\")\r\n"
    }
   ]
  }
 ]
}